modLoader="javafml"
loaderVersion="[36,)"
license="GNU GPLv3"

[[mods]]
modId="skyfarm_client"
version="1.0.6"
updateJSONURL="https://raw.githubusercontent.com/North-West-Wind/SkyFarmClient/main/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/sky-farm-client"
displayName="Sky Farm Client"
credits="Thanks to Clear Skies and Botania"
authors="NorthWestWind"
description='''
Client-side enhancements for Sky Farm.
'''

[[dependencies.skyfarm_client]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"

[[dependencies.skyfarm_client]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"

[[dependencies.skyfarm_client]]
    modId="botania"
    mandatory=false
    versionRange="[1.16.4-413,)"
    ordering="AFTER"
